image:  atlassian/default-image:latest
pipelines:
   branches:
     development:
     - step:
         name: Deploy to development
         deployment: test
         script:
           - ssh cicd@xx.xx.xx.xx docker exec <container-id> bash -c ./deploy.sh

